### PR TITLE
Disks12

### PR DESCRIPTION
**Pull request by andrewbird**
@stsp In light of the conversation in #445 about RxDOS lack of redirector support, is it worth merging this?

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
Why not, we have another DOSes
w/o redirector too...

**Comment by ecm-pushbx** [comment]
As you can see in my mak.sh script, the RxDOS kernel (both the RxBIO and RxDOS parts) now builds with only NASM. (This is why I branched the 7.21 "release".) However, it is certainly far from useable.

**Comment by stsp** [comment]
@ecm-pushbx Since quite a lot of people
seems to be interested, would you mind to
give a brief description of your goals?
Why do you develop RxDOS, what do you
want it to evolve into, why don't you develop
freedos instead? (its just a question, I do not
imply that you should develop freedos instead)

**Comment by ecm-pushbx** [comment]
For low-level stuff I prefer assembly language instead of C, and this allows for a simpler toolchain. (As you probably know, Borland and OpenWatcom C compilers are both non-free, though the latter is "open" source.) I plan to create a somewhat complicated memory scheme (with sections like DOSENTRY, DOSDATA, DOSCODE, DOSINIT) which is easier to do in assembly using NASM's flat bin output, too. (NB I'm somewhat of a NASM fangirl.) i have occasionally contributed to the FreeDOS kernel. I guess the language is my most significant problem with it.

I've been looking at RxDOS since as early as 2008, soon after I began learning program logic work. I'm currently planning on small incremental progress, though major fixes may eventually need more rewriting. It's definitely not ready for use yet, nor in the foreseeable future.

As you can see on https://bitbucket.org/ecm/ I've fiddled with some other programs, most notably extending the FreeDOS debugger (lDebug), and optimising a TSR's installation and removal handling (RxANSI).

**Comment by stsp** [comment]
> you probably know, Borland and OpenWatcom C compilers are both non-free

We got to know this a hard way: if we
depend on freedos, then dosemu2 is
not going to be included into major
distros because of that toolchain problem.
RxDOS could help with this if it had the
redirector, and not otherwise.
Thanks for your explanation!

**Pull request merged**
