### PR TITLE
fatfs: remove casts and calculated offsets

### PR DESCRIPTION
**Pull request by andrewbird**
There are no functional changes with this patch, its purpose is purely for
readablity.

### CODE REVIEW

**Comment by stsp** [comment]
Thanks, looks good.

**Comment by stsp** [comment]
Grr, and now it doesn't boot.

**Comment by andrewbird** [comment]
Really? With gcc or clang compiler?

**Comment by stsp** [comment]
With anything.
Debugging now.

**Comment by andrewbird** [comment]
And on 32 or 64 bit?

**Comment by stsp** [comment]
64, but it doesn't matter I suppose, since your
patch doesn't reveal any deps on a bitness.

**Comment by andrewbird** [comment]
Whats the size of the struct? Is it 0x10?

**Comment by stsp** [comment]
0x18

**Comment by stsp** [comment]
OK, pre-existing bug then. :)

**Comment by andrewbird** [comment]
Then it's a real wonder that booting ever worked properly on 64bit as the data is initialized via the struct fields.

**Comment by stsp** [comment]
That's because actually only "block_hi" was
displaced before your patch, and its most always
zero. So your patch uncovered a really nasty bug.

**Comment by stsp** [comment]
Fix applied.

**Comment by andrewbird** [comment]
I've just built and tested again with your fix applied, all looks fine on 32bit. Thanks for cleaning up after me!

**Pull request merged**
