### PR TITLE
simx86: Make e_VgaMovs less cumbersome to use and clean it up.

### PR DESCRIPTION
**Pull request by bartoldeman**
This needed the definition of vga_read_dword that was missing in
vgaemu.c.

### CODE REVIEW

**Comment by bartoldeman** [comment]
Next patch from #156. Nearing the end, the rest of that PR is mostly about using cpatch for VGA reads, so the expensive part of `e_vgaemu_fault` can be completely eliminated.

**Comment by stsp** [comment]
This one regresses on ansi.com with vm86sim,
and vm86 (jit) crashes when starting win31:
```
ERROR: eVGAEmuFault: unimplemented decode instr at 7fd1e803cbdc: c6900788
```

**Comment by stsp** [comment]
Note that I already pointed to that regression
here: https://github.com/stsp/dosemu2/pull/149

**Comment by stsp** [comment]
I remember that patchset had many regressions
and got reverted. I thought you at least fixed them
before a re-submit. :)

**Comment by bartoldeman** [comment]
I checked it in #156 but it's so long ago that I probably missed something.. anyway good that by using small chunks we know where the issue is!

**Comment by stsp** [comment]
Well, but I bisected exactly that
chunk also back then. :) You can
see that in the referenced ticket.

**Comment by bartoldeman** [comment]
I think I found the issue (`*rsi+=dp,*rdi+=dp` should have been `esi+=dp, edi+=dp`), can you try again please?

**Comment by bartoldeman** [comment]
This was just by observation: I can't reproduce your windows issue (works for me) and don't have ansi.com, just nani.sys and nnansi.com.

**Comment by stsp** [comment]
ansi problem is fixed, but windows still crashes.

**Comment by stsp** [comment]
In SIM mode windows works, jit crashes.

**Comment by stsp** [comment]
Also IIRC there were some siglongjmp()
patches in the old patch-set. The care must
be taken to not jump out of a signal stack,
or it will never be re-enabled because of
the new flag usage. I tried to not interfere
with anything, so I think that flag is not used
in fullsim mode, but in sim mode things are
more complicated. So, while I hope its still
safe, something to double-check.

**Comment by stsp** [comment]
OK, let me help you. :)
```
diff --git a/src/base/emu-i386/simx86/sigsegv.c b/src/base/emu-i386/simx86/sigsegv.c
index c8020b50a..15f2a0f95 100644
--- a/src/base/emu-i386/simx86/sigsegv.c
+++ b/src/base/emu-i386/simx86/sigsegv.c
@@ -260,6 +260,16 @@ int e_vgaemu_fault(sigcontext_t *scp, unsigned page_fault)
      * this will cause the cpuemu to fail.
      */
     switch (*p) {
+/*88*/ case MOVbfrm:
+               if ((_err&2)==0) goto badrw;
+               if (p[1]!=0x07) goto unimp;
+               e_VgaWrite(LINP(_edi),_eax,MBYTE);
+               _rip = (long)(p+2); break;
+/*89*/ case MOVwfrm:
+               if ((_err&2)==0) goto badrw;
+               if (p[1]!=0x07) goto unimp;
+               e_VgaWrite(LINP(_edi),_eax,(w16? DATA16:DATA32));
+               _rip = (long)(p+2); break;
 /*8a*/ case MOVbtrm:
                if (_err&2) goto badrw;
                if (p[1]==0x07)
```

This works.
You removed that in a prev patch.

**Comment by bartoldeman** [comment]
Yes I know that, but those should not be necessary any more :) I should not need to re-add those (unless `devel` is also broken!!)

**Comment by stsp** [comment]
devel may be broken in many ways, but
at least when I switch to it from your branch,
then the same win31 works.

**Comment by bartoldeman** [comment]
I still couldn't reproduce but I did some code review: the `return` in `rep_movs_stos` was the issue, as this caused `in_cpatch` not to be reset, which in turn caused the code sequence to skip Cpatch.. In the earlier sequence in #156 there was not yet the sequence:

```
	InCompiledCode++;
	in_cpatch--;
```
so it was ok to `return;` back then.

Should be fixed now :)

**Comment by stsp** [comment]
Seems to work, thanks!

**Comment by bartoldeman** [comment]
About `siglongjmp`, yes that was moved in the last patch of #156 
It only applies to `fullsim` (`in_dpmi_emu`) and I last touched the sigsetjmp in 20440df and you did something similar to the last past of #156 (and much more) in fea03d79b2.

**Pull request merged**
