### PR TITLE
umb: Split out common device driver stuff

### PR DESCRIPTION
**Pull request by andrewbird**
Not ready for you to pull yet, but opened this as somewhere to discuss.
Do you think it's worth pursuing using a common file and macro to define the header and standard functions of a device driver? Is there anything else you'd turn into a macro (InitError exit method etc)?

### CODE REVIEW

**Comment by stsp** [comment]
Yes, looks cool, except that it should
probably not be `.S`. I think either `.h`
or `.inc` - need to take a look into what
other projects do (too limited internet
access right now).

Yes, the next thing to generalize is the
entire umb.sys code because it is the
same also in ems.sys.

**Comment by andrewbird** [comment]
Mmm, it's hard to find a definitive answer on the file type. Google suggests mainly '.h' but that doesn't seem right as it's normally a C header. or perhaps shared with '#ifdef assembler'. I also found .'i', but not many occurrences of that. Perhaps no one cares, but as you say it's best to avoid .S and other well known ones as there may be Makefile rules using them.

**Comment by andrewbird** [comment]
I rebased my branch on devel as I wanted the latest emufs.S, so when I push it probably won't apply to your umb_sys branch.

**Comment by stsp** [comment]
Well, umb_sys just needs a generalization
of the umb code. If it is not what you do, then
whatever branch you want, is appropriate.

**Comment by stsp** [comment]
I think you should really google for `inc`.
It mainly comes from windows world, but
its exactly for that purpose.

**Comment by andrewbird** [comment]
I think I'm going to drop this for now, perhaps I'll come back to it later.

**Pull request closed without merging**
