### PR TITLE
Automatically make the dev_name virtual connection

### PR DESCRIPTION
**Pull request by runderwo**
RFC only to explain what I meant.

### CODE REVIEW

**Comment by stsp** [comment]
You can simply create the persistent rawmidi names
with .asoundrc. So I don't see the clear advantage in
what you propose. Of course searching for SND_SEQ_PORT_TYPE_MIDI_MT32
sounds also quite nice, so maybe we can have the both ways.

**Comment by stsp** [comment]
Of course dosemu will eventually start munt itself,
but your idea of searching for SND_SEQ_PORT_TYPE_MIDI_MT32
is plausible regardless, as it may happen to utilize
the mt32-compatible hardware.

**Comment by stsp** [comment]
So we now have the munt plugin.
However if you implement the SND_SEQ_PORT_TYPE_MIDI_MT32
as a separate plugin (in the same file, just register it separately),
then it would likely be fine to merge.

**Comment by stsp** [comment]
This PR seem to contain the useful code, so lets
keep it opened.

**Comment by runderwo** [comment]
What's useful about it?  I gave up because I couldn't understand what direction you wanted to go.

**Comment by stsp** [comment]
We don't have munt-devel packaged by
any distro AFAIK, and as such, it is still
possible that people will miss the munt
plugin in dosemu, yet having the munt
installed as an alsa sequencer.
For such cases I think looking for
SND_SEQ_PORT_TYPE_MIDI_MT32
might be useful, and since you have the
code that can be used for that, I think it
is useful.

**Comment by stsp** [comment]
@runderwo Where is your patch?
This ticket seems to be totally messed up.

**Comment by stsp** [comment]
Ah, perhaps here:
https://github.com/stsp/dosemu2/pull/141/commits/354dac7f828232bdfaecd39ed288ae2d13e6ecaf

**Comment by stsp** [comment]
> For such cases I think looking for
> SND_SEQ_PORT_TYPE_MIDI_MT32
> might be useful, and since you have the
> code that can be used for that, I think it
> is useful.

But this code is not looking for MT32 port...
In fact, I can't understand what it actually
does, and there is no description.
So what does it do?

**Pull request closed without merging**
