### PR TITLE
Travis ci 08

### PR DESCRIPTION
**Pull request by andrewbird**
Add a little infrastructure + FCBDelete / FCBFind tests.

### CODE REVIEW

**Comment by stsp** [comment]
Why do we need yet another compiler?

**Comment by andrewbird** [comment]
> Why do we need yet another compiler?

I find myself always doing tests in assembler, purely because I'm unsure of when I have to do things like [this](http://www.delorie.com/djgpp/v2faq/faq18_4.html) in djgpp. I'm quite happy in assembler though, except when I want to print values other than strings or chars as then it becomes labourious. I'll drop it until I have a real need.

**Comment by stsp** [comment]
You never have to do this in djgpp,
we discussed that before. :) So my
point is that djgpp just suits. Please
let me know when its not the case.

**Comment by andrewbird** [comment]
> You never have to do this in djgpp,
we discussed that before. :)

Yes and thanks for that, I just haven't had my true 'Ah Hah' moment yet, hence my still being unsure! I'll get there eventually.

I force pushed the branch now without.

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
