### PR TITLE
FDPP: Rename autofdpp.bat to fdppauto.bat

### PR DESCRIPTION
**Pull request by andrewbird**
More consistent naming as mentioned in #771.

### CODE REVIEW

**Comment by stsp** [comment]
Ну и глупо.
You and @bolle732 will be responsible for that
change. Please take care to explain the users
why their setups broke again.

**Comment by andrewbird** [comment]
> Please take care to explain the users
why their setups broke again.

Okay I'm fine with that :smile:

**Comment by andrewbird** [comment]
> Ну и глупо.

Google translate!

**Comment by stsp** [comment]
> Google translate!

It translates that very differently depending on
whether the first letter is capital or small.
I'd say the translation is somewhat correct only
with small letter at the beginning, like "ну и глупо."
The translation it gives for the original phrase,
does not look adequate to me.

**Pull request merged**
