### PR TITLE
Travis ci 04

### PR DESCRIPTION
**Pull request by andrewbird**
Add FreeDOS 1.20 into the test regime,TestCase specific skipping and FCB read/write tests.

### CODE REVIEW

**Comment by andrewbird** [comment]
It looks like my ISP doesn't like me using their free webspace for hosting a FreeDOS tarfile and have silently deleted it. Have you any suggestions where it could be hosted that Travis can access?

**Comment by stsp** [comment]
Ideally - get from freedos mirror and unzip.

**Comment by andrewbird** [comment]
The test files have some other self generated stuff in there like boot blocks etc, not so important for FDPP but useful for testing boot process of other DOSes. I spoke to my ISP and the file hadn't actually disappeared, just some misconfigured DNS causing hits on a server that didn't have the file!
I've just pushed a version using the python test runner rather the unsupported nose as pointed out by @stuaxo.

**Comment by stsp** [comment]
Thanks.

**Pull request merged**
