### PR TITLE
mkfatimage16: put volume label last, misc fixes

### PR DESCRIPTION
**Pull request by ecm-pushbx**

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
For the future, please write more
description into the commit message.

**Comment by ecm-pushbx** [comment]
Do you mean the pull request's description comment, or the individual commits' messages?

**Comment by stsp** [comment]
Please fill in both, but "individual commits' messages"
are more important because they stay forever and help
people finding out why this and that was done.
In fact, if you ever try to contribute to linux kernel,
you'll find out that description is getting the enormous
amount of attention; patches are not taken unless
the very verbose description is provided. This is not
the case here, but the patch that moves volume label
could better have the proper description with it.

**Comment by ecm-pushbx** [comment]
Okay, thanks, will do!

**Pull request merged**
