### PR TITLE
Travis ci 06

### PR DESCRIPTION
**Pull request by andrewbird**
Testing tidyups and a new test

### CODE REVIEW

**Comment by stsp** [comment]
Would you like to add the multilib build?

**Comment by andrewbird** [comment]
Oh yes I forgot about that, will do!

**Comment by andrewbird** [comment]
I added the multilib package. It doesn't really do a lot (if anything) yet, as I need to split out some of the common stuff from `test_dos.py` so I can reuse it to make a simple single run of the cpuemu self tests.

**Comment by stsp** [comment]
Then lets drop the gcc-multilib commit until
the actual build works.

**Comment by andrewbird** [comment]
okay

**Comment by stsp** [comment]
Have you dropped it?

**Comment by andrewbird** [comment]
not yet, 2 mins

**Comment by andrewbird** [comment]
it's gone now

**Comment by stsp** [comment]
Thanks!

**Comment by andrewbird** [comment]
I added the cpuemu tests in https://travis-ci.com/andrewbird/dosemu2/builds/139618058 / https://github.com/andrewbird/dosemu2/tree/travis-ci-07 it looks like a few things need fixing

**Comment by stsp** [comment]
Most of the diff is the addresses in the registers.
The test must be changed to eg print deltas of
esi/edi on movs operations, rather than the absolute
values.

**Comment by andrewbird** [comment]
Yes, I agree. At the moment I'm trying to split up the test-i386.c into smaller chunks so I can test things like just a single operation. However looking at 
https://github.com/stsp/dosemu2/blob/17150434c0bb9d804010fc4ba4d2d7eda150086c/src/tests/test-i386.c#L3000-L3039

I can't see how I can call say just the `test_add()` under native, there seems to be some magic going on?

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Thanks, you are really good aren't you!

**Pull request merged**
