### PR TITLE
Implement paging for vm86 in KVM and handle exceptions in _dosemu_fault.

### PR DESCRIPTION
**Pull request by bartoldeman**
This fixes vgaemu memory accesses and Windows 3.1.

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
Win3.1 goes further but still doesn't boot.
In any case, perhaps this is "good enough"
to merge to devel?

**Comment by stsp** [comment]
I have merged this to devel.
As long as it is not on by default, there is no regression,
and it mostly works anyway.

**Comment by bartoldeman** [comment]
Just wondering, where does Win 3.1 hang for you now? I have it bringing up the GUI and then complaining with a GPF in PROGMAN as soon as I move the mouse but this is not KVM specific.

I have an old DOSEMU from the SF git where Win 3.1 does not complain about PROGMAN and is usable but have not tried that with KVM.

**Comment by stsp** [comment]
I have it working fine without KVM, and
GPF in progman - only with KVM.
Seems like the same is true for other people as
well: the bug reports were only about an installer.
In any case, I'll look into an installer problem (can
reproduce) and maybe that will give some clue.

**Comment by bartoldeman** [comment]
Ok, I can see now. With KVM for 64 bit dosemu it doesn't get as far than on 32-bit (or 64-bit with cpuemu). That will give me a clue of where to look.

**Comment by stsp** [comment]
It seems windows support is very unstable:
installer randomly crashes, rarely getting to
the point of the reported bug.
So I wonder if this will give you a clue or a
wrong spot...

**Comment by bartoldeman** [comment]
I did a bisect. This commit causes me trouble:

commit 21273a1c15aac70f7aa93ba3fcdbce488dfc4957
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Sep 19 23:22:00 2015 +0300

    msdos: port mouse callbacks to rmcb

If I go to the state before, apply the KVM patches there (just a small trivial conflict in mapping.c), Win 3.1 works perfectly.

After commit 21273a1, it always complains about PROGMAN GPF if I move the mouse, or earlier with KVM but that is timing dependent (if I run dosemu -D+9M it goes further).

**Comment by stsp** [comment]
Thanks!
Are you using ps2/int15 or int33 mouse driver?

**Comment by stsp** [comment]
So am I right that the problem doesn't happen
for you on 64bit with cpuemu?

**Comment by bartoldeman** [comment]
It's been a long time, so I am not even sure how to use int33 for win. I did not do any special setup in dosemu.conf or win.ini, and the logs indicate PS/2.

The problem happens for me too on 64bit with cpuemu -- as soon as I move the mouse into the X window PROGMAN gives the GPF.

**Comment by stsp** [comment]
Ok, I'll try ps2 in the evening.
To get int33 you need a mouse driver from winos2.
It works much better than ps2 in non-grab mode.

**Comment by stsp** [comment]
Fixed.
Hope this will help you to fix the KVM
regression, which is still there.

**Comment by bartoldeman** [comment]
Thanks, I will check

with the winos2 mouse driver I can see it changes from working to the crash you are seeing with

commit d6032cf742502c7068336941718aebe3299a29e9
Merge: 1f0aa1a 3b1dba1
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sun Oct 11 05:11:27 2015 +0300

    Merge branch 'msdos_ldt' into devel

I'll check the mprotect's -- perhaps the ldt pages are not properly protected with KVM.

**Pull request merged**
