### PR TITLE
Cleanups 04

### PR DESCRIPTION
**Pull request by andrewbird**
This should resolve issue #60

### CODE REVIEW

**Comment by stsp** [comment]
I cherry-picked the first one.
Please open a separate request if the second
is worth it, but with a better changelog then, please. :)

**Comment by andrewbird** [comment]
Mmm, I'm not sure it's worth it. Maybe it's just a quirk of my compiler version. The errors are

~~~
    gcc -m32 -Wall -O2 -g -fno-strict-aliasing  -lm -o test-i386 test-i386.c test-i386-code16.S test-i386-vm86.S
    /tmp/ccWSgwff.o: In function `test_fops':
    src/tests/test-i386.c:778: undefined reference to `sincos'
    src/tests/test-i386.c:783: undefined reference to `fmod'
    src/tests/test-i386.c:787: undefined reference to `tan'
    src/tests/test-i386.c:788: undefined reference to `log'
    src/tests/test-i386.c:789: undefined reference to `exp'
    src/tests/test-i386.c:790: undefined reference to `atan2'
    src/tests/test-i386.c:792: undefined reference to `asin'
    src/tests/test-i386.c:793: undefined reference to `acos'
    src/tests/test-i386.c:794: undefined reference to `atan'
    src/tests/test-i386.c:784: undefined reference to `sqrt'
    collect2: error: ld returned 1 exit status
    make: *** [test-i386] Error 1
~~~

**Comment by stsp** [comment]
Maybe you have --as-needed ld flag by default?
With -Wl,--as-needed I am getting the same.
However, the rest compiles fine?

**Comment by andrewbird** [comment]
Yep, it looks like Ubuntu patched gcc again 
http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/gcc-4.8/trusty/view/head:/debian/patches/gcc-as-needed.diff
Everything else compiled ok, so I'm thinking not to bother with this

**Comment by stsp** [comment]
Applied with a better changelog, thanks
for investigating.

**Pull request closed without merging**
