### PR TITLE
Present a menu when system FreeDOS is available

### PR DESCRIPTION
**Pull request by jschwartzenberg**
Basically the menu you wrote about.

The terminology isn't great yet though...

### CODE REVIEW

**Comment by stsp** [comment]
That's not quite correct, I suppose instead
of "install freedos" you should say something
like "use existing freedos installation" because
by installing we now mean something different
rather than to create a couple of symlinks to the
system-wide stuff.
Also what is user-provided DOS?

**Comment by jschwartzenberg** [comment]
Yes, I can update that string.

The user-provided DOS is an option that was already there. It allows specifying a path from which DOSEMU can then copy a very basic DOS system (as for as I see). I think further developments will make that option obsolete at some point.

**Comment by jschwartzenberg** [comment]
I updated the string. I noticed I mistook your question. User provided DOS brings you to the second menu. This uses either the installdos script or "Use a different DOS." which is what I explained about.

**Comment by stsp** [comment]
OK, lets merge this, but we really need a
second menu of the available doses.

**Comment by jschwartzenberg** [comment]
You mean doses other than FreeDOS? They are currently unsupported by the scripts but I indeed plan to add that.

**Pull request merged**
