### PR TITLE
Mount bat

### PR DESCRIPTION
**Pull request by stuaxo**
Here are a couple of commits to add mount.bat

Initially I thought dosemu mount was dumb and only supported  ```mount q ~/dosprogs```

It has a bunch of other params they don't list in ```/?``` and the syntax seems sane.

#74

### CODE REVIEW

**Comment by stsp** [comment]
OK but IIRC you wanted to look into changing
the lredir params handling.
Won't it require serious changes to this script then?

**Comment by stuaxo** [comment]
That's fine I just put it together today and it can be nuked later if needed, it's own params are all the same as dosboxes.

I realised mount *should* be replaced with an executable, so it can be used from batch files that work on dosbox - as it is a batch file 'mount' will quit the current batch file :/

For lredir, I'm learning it by first fixing it to be compliant with it's own comments + cleaning up the code to be in the same style as unix.c...   

lredir_main is quite complex, so I don't want accidentally get rid of functionaliy.


Simple drive mapping should probably be compatible (displaying a warning) - so that people can still boot dosemu on upgrading to dosemu2 other parameters probably have the freedom to change.


To further untangle lredir - I could really do with examples of redirecting LPT/COM and redirecting to floppy images.

**Comment by stsp** [comment]
> dosbox - as it is a batch file 'mount' will quit the current batch file :/

I wonder if there is some freecom-specific trick to avoid using 'call' cmd...

> Simple drive mapping should probably be compatible (displaying a warning) - so
> that people can still boot dosemu on upgrading to dosemu2 other parameters probably
> have the freedom to change.

That would be too complex and no clean-up at all.
How about introducing the lredir2 then?

> To further untangle lredir - I could really do with examples of redirecting LPT/COM
> and redirecting to floppy images.

No COM or floppy.
As for lpt, the syntax is:
lredir lpt5 p
will map DOS lpt5 to dosemu's $_lpt5

**Comment by stuaxo** [comment]
So I gave this a go, not sure it's working properly - I have lpt1 and lpt5 printing to PDF
```
# dosemu.conf
$_lpt1 = "lpr -P PDF"
$_lpt5 = "lpr -P PDF"
```

Printing to lpt1 works, then I did 

```
lredir lpt5 p
LPT5 = LINUX\PRN\5 attrib = READ/WRITE
```

But if copying a file to LPT5 just creates a file called 'LPT5'

**Comment by stsp** [comment]
Hmm, how did it ever work...
Fixed.

**Comment by stsp** [comment]
So if we are to have an incompatible
lredir2, the printer syntax can be even
simpler:
lredir2 -p
may mean redirect all LPTs above $_lpt3, if any.

**Comment by stsp** [comment]
I implemented lredir2.
mount.bat should use that because lredir
is going to be deprecated.

**Comment by stuaxo** [comment]
Ah, OK ... I guess I should have been quicker in my own branch - I'll have a look ..

**Pull request closed without merging**
