### PR TITLE
Travis ci 02

### PR DESCRIPTION
**Pull request by andrewbird**
Add another 16 tests now that we have DJGPP compiler available.

### CODE REVIEW

**Comment by stsp** [comment]
But why are the C/asm test files all in the python script?

**Comment by andrewbird** [comment]
Most of the C/ASM are actually templates and the dynamic parts are substituted in before each test. So one template might be used for many tests, see `test_*_fcb_rename_*`. If I move them to separate files, I end up just having to do that substitution external to the test file anyway. That said, I don't like size of `test_dos.py` and I'm looking to refactor somehow.

**Comment by stsp** [comment]
At least when we are talking about
the C tests, you can just pass the
arguments to the binary, instead of
making a source-level templates.

**Comment by andrewbird** [comment]
Yes.

**Comment by stsp** [comment]
OK, thanks.

**Pull request merged**
