### PR TITLE
Install dos

### PR DESCRIPTION
**Pull request by jschwartzenberg**
I merged devel in and changed the code so that as proposed in #302:
- The script puts its dos in c
- d always points to the systemwide freedos

### CODE REVIEW

**Comment by stsp** [comment]
Oh, this ticket is a complete mess!
Could you please create a sane one?
In fact, maybe you can simply rebase
your branch to devel, instead of doing
the merge?

**Comment by jschwartzenberg** [comment]
I don't think it will make a difference as long as the PR is against install_dos. Maybe you could rebase your install_dos branch against devel? Then I think the differences here should disappear.

**Comment by stsp** [comment]
OK, lets just merge this.
I'll have a look later anyway.

**Comment by stsp** [comment]
@jschwartzenberg would you like to re-spin that?
Now as we don't have install.c, these scripts no longer
need to depend on anything in dosemu2 or on my
development plans. They can just be put in as contrib.
So you can just make sure they still work, write some
minimal TUI and re-submit?

**Pull request merged**
