### PR TITLE
Locales: Add en_GB -> cp858 mapping

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
Have you tested it with new json-c?

**Comment by andrewbird** [comment]
No, but looks fairly trivial, I can't imagine it could be wrong :smile:

**Comment by stsp** [comment]
Your patch is likely correct, but my functionality
may have bugs. :) The situation with json-c is
upsetting, to say the least.

**Comment by stsp** [comment]
I added the bug report:
https://bugs.launchpad.net/ubuntu/+source/json-c/+bug/1863148
If you subscribe to it or indicate that
it affects you, the points will be raised.

**Pull request merged**
