### PR TITLE
Dosdebug 38

### PR DESCRIPTION
**Pull request by andrewbird**
dosdebug: Tidy up display of MCBs
 
    1/ Use single loop and logic for MCB display
    2/ Add display of DOS data subsegments
~~~
    dosdebug> mcbs
    dosdebug>
    
    ADDR(LOW) PARAS  OWNER
    0290:0000 0x000d [DOS]
      => ADDR      PARAS TYPE USAGE
         0291:0000 0x000c [F] Files
    029e:0000 0x9d60 [FREE] (END)
    
    ADDR(UMA) PARAS  OWNER
    9fff:0000 ------ [LINK]
    c300:0000 0x0215 [DOS]
      => ADDR      PARAS TYPE USAGE
         c301:0000 0x0009 [D] Driver (EMS)
         c30b:0000 0x0008 [D] Driver (EMUFS)
         c314:0000 0x0020 [B] Buffers
         c335:0000 0x00cf [F] Files
         c405:0000 0x008f [L] CDS Array
         c495:0000 0x0080 [S] Stacks
    c516:0000 0x0006 [FREE]
    c51d:0000 0x12c1 [COMMAND]
    d7df:0000 0x081f [FREE]
    dfff:0000 ------ [LINK]
    f000:0000 0x0513 [FREE]
    f514:0000 0x0619 [COMMAND]
    fb2e:0000 0x0090 [COMMAND]
    fbbf:0000 0x0040 [COMMAND] (END)
~~~

### CODE REVIEW

**Comment by stsp** [comment]
A few notes:
- The code in the first patch looks very familiar.
How about just printing them in the "mcbs" command,
properly tab-ified?
- By commonizing mcb traversals I meant, would it
be possible to traverse them with a single piece of
code (loop), rather than to duplicate the same code
loop for LMA and UMA?

**Comment by andrewbird** [comment]
okay, I'll try again later.

**Comment by andrewbird** [comment]
I force-pushed and updated the first message in this thread to reflect what's in the current commit.

**Comment by andrewbird** [comment]
Or perhaps you prefer the indention below?
~~~
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER     TYPE  USAGE
0290:0000 0x000d [DOS]
0291:0000 0x000c            [F]  Files
029e:0000 0x9d60 [FREE] (END)

ADDR(UMA) PARAS  OWNER     TYPE  USAGE
9fff:0000 ------ [LINK]
c300:0000 0x0215 [DOS]
c301:0000 0x0009            [D]  Driver (EMS)
c30b:0000 0x0008            [D]  Driver (EMUFS)
c314:0000 0x0020            [B]  Buffers
c335:0000 0x00cf            [F]  Files
c405:0000 0x008f            [L]  CDS Array
c495:0000 0x0080            [S]  Stacks
c516:0000 0x0006 [FREE]
c51d:0000 0x12c1 [COMMAND]
d7df:0000 0x081f [FREE]
dfff:0000 ------ [LINK]
f000:0000 0x0513 [FREE]
f514:0000 0x0619 [COMMAND]
fb2e:0000 0x0090 [COMMAND]
fbbf:0000 0x0040 [COMMAND] (END)
~~~

**Comment by stsp** [comment]
Marvelous!
Thanks.

**Pull request merged**
