### PR TITLE
Rename win31 to win3x as it also applies to win30 and win311 (and

### PR DESCRIPTION
**Pull request by jschwartzenberg**
Chinese win32?). Use an enum to indicate the the mode instead. This
should not have any functional impact.

### CODE REVIEW

**Comment by jschwartzenberg** [comment]
Here's the pull request I'd sent for the win3x_mode stuff. Let me know whether you like or dislike this :)

**Comment by stsp** [comment]
Almost no one runs win 3.0 under dosemu,
plus it is not supported under anything else
than real mode. So how about keeping the
3.1 title for standard/enh and write "3.0" for
real?

**Comment by jschwartzenberg** [comment]
Sounds ok to me. Note that this would not properly cover:
- the beta versions of Windows 3.1 that still had real mode
- Windows (for Workgroups) 3.11
- Windows 3.2 Chinese

**Comment by stsp** [comment]
OK, applied then, thanks.
It all doesn't really matter after all.
Does windows beta work in real mode
under dosemu btw?

**Comment by jschwartzenberg** [comment]
I never tried it, but should yeah. I suspect the early 3.1 betas were very similar to 3.0.

**Pull request merged**
