### PR TITLE
MPU401 intelligent mode

### PR DESCRIPTION
**Pull request by runderwo**
We can discuss here.

### CODE REVIEW

**Comment by runderwo** [comment]
I've rebased and used add_thread_callback(), but still the following two problems remain:
1. hogthreshold slows music down unless a key is held down
2. hogthreshold=0, fast notes in music (fast interrupt rate) slows down the song

For reference, the only I was able to make the music work correctly by increasing config.freq and sending SIGIO to main thread myself.  Since add_thread_callback() does the latter, I wonder how to avoid increasing config.freq, and also how to make hogthreshold irrelevant.

**Comment by stsp** [comment]
Hi Ryan, why do you want to add such an option?
It makes no sense, we only emulate sb16. And we
do not add the options that only go into environment
var.
If you want blaster.com to detect that at run-time,
just use the appropriate DSP command to get the
SB version.

Also you need to move things to separate file, or
explain why exactly this should belong to dspio.c.

**Comment by stsp** [comment]
If in the future we add sb_type, it will control
the DSP version (see sb16.h for SBxx_ID consts) and
the set of DSP commands, but not blaster.com.

**Comment by stsp** [comment]
To avoid hogthreshold, you simply need to call
reset_idle() in the right places. For example when
the app writes a new sample.

**Comment by stsp** [comment]
Why do you add thread to dspio.c?
You should add the thread to your own code,
if needed. Although since your code does not
seem to do any CPU-intensive computations
like midi synth, I wonder why do you even need
a thread? The things will be much simpler if
you don't, IMHO.

**Comment by runderwo** [comment]
Sorry for the cruft in the branch, the aim of this review is to solve the present problems I mentioned only (interrupt handling is too slow for the intelligent mode app).

Regarding blaster.com changes, it's intended to be for dynamic configuration in the future.

**Comment by stsp** [comment]
So remove the thread, the interrupts will be fast.

**Comment by runderwo** [comment]
I removed the thread, but it's still too slow during fast parts.

Also, I'm not sure what the right place for reset_idle() is.  hogthreshold takes over to prevent the VM code from running when there is no keyboard input, right?  So would I need to reset_idle() in every MPU timer tick as long as some MPU track is actively playing?

**Comment by stsp** [comment]
So run_sound() in dspio.c is affected by the
config.freq IIRC, but you seem to use dspio_process_midi(),
which is not affected. But try to call run_sound()
from dspio_timer() - see if that changes anything.

Hogthreshold takes not when no keyboard input.
It depends on what an app is doing. If it polls the
keyboard and there is no input, it idles.
Yes, try reset_idle() on timer ticks. Also play with
the values you pass to that func.

**Comment by stsp** [comment]
This pull request has conflicts.

**Pull request closed without merging**
