### PR TITLE
KVM IDT changes (part 2)

### PR DESCRIPTION
**Pull request by bartoldeman**
Here are some of the requested IDT changes:
1. DPMI in KVM will now use IDTs > 0x10 directly for software interrupts.
2. Extended direct IDT use to ints 0x11-0x1f (since those exceptions can never happen)
3. Eliminate the special 0xff hw int injection, by using ioctls to get and set registers. I'm not using the kvm_sync_regs structures since that requires new-ish kernels (4.18+) and the speed is not affected much since the ioctls only apply for signals, and sets only if the registers have changed (which either means a hardware int or some kind of callback / coopthread magic).
Ideally I'd inject hardware ints into KVM, and maybe even use its builtin PIC but that's for another day (then hardware ints go via the IDT and must then be reflected to the vm86 IVT).

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
But you do not seem to be removing the
state save/restore asm from kvmmon.S,
even if the ioctls can be used?

**Comment by stsp** [comment]
So if I understand correctly, the TODO spelled here:
https://github.com/stsp/dosemu2/issues/982#issuecomment-573312835
would now look like:

1. get rid of manual registers save/restore (still in kvmmos.S?)
2. use DPL=3 for IDT even in default case (still have kvm_set_idt_default())
And a slightly more difficult one:
4. make it to work with simx86's page protection

**Comment by bartoldeman** [comment]
1. this is not efficient as far as I can see. Since KVM traps at the ring-0 HLT for exceptions, the cs:eip is the ring-0 cs:eip and we need to access the ring-0 stack any way to fetch the original cs:(e)ip, eflags, ss:(e)sp, for vm86 the segment registers, and the error code. So instead of needing a system call to fetch and restore the registers, for exceptions it's faster to just push/pop them on the ring-0 stack and fetch from there.
2. this is easy: #1008
3. I'll have a look
I have some more ideas, but I may not do all of them soon
4. sort out dirty page tracking properly incl. LDT, VGA banked memory (see some older PRs)
5. use KVM_INTERRUPT to inject hw ints
6. use IOPL=3 in the guest: for DPMI code that makes cli_timeout unnecessary (this means working with IF instead of VIF and asking KVM for an interrupt window instead of setting VIP)
7. use the in-kernel IRQCHIP PIC
8. use the in-kernel PIT (optionally, requires 6)
9. implement VCPI (optionally, as that needs disabling DOSEMU's DPMI and allows the guest to take over the IDT, paging, etc.)

**Comment by stsp** [comment]
Oh, nice todo list, but we need to prioritize
some items (and de-prioritize others) in order
to make the releases. Obviously the items
starting from 5, are not relevant for the nearest
release (if we want it to ever happen).
OTOH there is some problem with KVM that
currently only @jschwartzenberg can reproduce,
but it happens to me too, then stopped happening.
Its just that many realmode games are having
some weird lock-ups. I was not able to get back
to this, but if you have some time, I am sure @jschwartzenberg 
will set up an ssh/vnc access for you.

**Comment by jschwartzenberg** [comment]
I had to look up the issues: #918 and #922
I can indeed provide access. Maybe the CPU is relevant, I can only reproduce those on my Intel Core2 Duo system, not on my i5.

**Comment by stsp** [comment]
I am sure that happened on my amd
system too, or I wouldn't believe you. :)
But it disappeared just as suddenly
as started to happen.

**Comment by jschwartzenberg** [comment]
I am suspecting microcode updates now with all the CPU bug patching going on lately.

**Comment by stsp** [comment]
Are you available for ssh now? :)

**Comment by jschwartzenberg** [comment]
Sorry I didn't expect you'd do it that late on Sunday! I am ready now if you have time ;)

**Comment by stsp** [comment]
Now my internet connection is
down because of some isp problems.

**Pull request merged**
