### PR TITLE
Alsa: redirect library logging from stderr to logfile

### PR DESCRIPTION
**Pull request by andrewbird**
Tidies up log destination from stderr to dosemu's boot.log with debug
flag -S, mentioned in issue #227

### CODE REVIEW

**Comment by stsp** [comment]
How about using error() and make sure it
can be suppressed on -q?

**Comment by andrewbird** [comment]
@stsp I looked further at error() / verror() and whilst they logged nicely to boot.log without too much effort on my part, they still write the message to stderr. I know you mentioned extending them to honour the -q flag, but that's not really the use case I was looking to fix. I wanted to clean up the standard startup without needing to specify 'be quiet' flag.  I appreciate your comment about the -S debug flag not always being in operation and the subsequent message loss, and so I've changed the logging to be unconditional. I do think now that no stderr message content will be lost and now of course they end up in permanent storage within the log file. 
I hope you can understand why I find the stderr message so annoying, and consequently why I propose to fix it in this way.

Andrew

**Comment by stsp** [comment]
> I hope you can understand why I find the stderr message so annoying, and consequently
> why I propose to fix it in this way.

But this is really, really not the fix.
If alsa tells you lots of messages, you can, either:
- install the missing packages
- disable the sound in dosemu config
In both cases your setup will became consistent.
So how about simply advising the user (by extending
the error message) to either install things or disable
sound? Then he'll be able to quickly get rid of the
annoying errors.

**Comment by stsp** [comment]
Maybe we can find a simple compromise
if you don't want to rework the patch. How about
choosing between dbug_printf() or error()
depending on (err & !config.quiet)?

**Comment by andrewbird** [comment]
Hi @stsp, I've added your suggestion and confirmed that the quiet flag(-q) is observed now for all ALSA messages on stderr. I'm not sure if ALSA ever emits non error messages, but if so they should be logged to boot.log and not stderr in the default non quiet case.

Thanks,

Andrew

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
