### PR TITLE
dos2linux: find dos path from linux without cds

### PR DESCRIPTION
**Pull request by andrewbird**
This patch is a work in progress towards fixing #125, please *DO NOT* apply it in its current state. I would like some advice please on how to complete the fix? I have all previously failing(#125) DR-DOS versions working with this patch and the following hack
```C
diff --cc src/dosext/mfs/lfn.c
index 122e54f,122e54f..fe2314c
@@@ -171,7 -171,7 +171,7 @@@ void make_unmake_dos_mangled_path(char 
  	*dest++ = current_drive + 'A';
  	*dest++ = ':';
  	*dest = '\\';
--	src = fpath + strlen(drives[current_drive].root);
++	src = fpath ; //+ strlen(drives[current_drive].root);
  	if (*src == '/') src++;
  	while (src != NULL && *src != '\0') {
  		char *src2 = strchr(src, '/');
```
It feels to me like I should be making a new function instead of 'make_unmake_dos_mangled_path' outside of mfs/lfn.c that doesn't utilise 'drives[current_drive]' and referencing that from unix.c. However I have to say that I don't fully understand what 'make_unmake_dos_mangled_path' is doing

### CODE REVIEW

**Comment by stsp** [comment]
Could you please document your ideas before coding?
What/where cds is used for now, and how you are replacing its uses?
What is the reason of using get_fat_fs_by_drive()?
Why lfn.c is such a big deal, would it be enough to
get rid of cds only in mfs.c?
The things like current_drive etc can simply be
got by calling to DOS functions.

**Comment by andrewbird** [comment]
I understand from your previous comments that requiring cds in mfs.c could be removed if it were rewritten. I'm sure that is the best long term goal, but for now the only ill effect im seeing due to the redirector being un available is the inability to execute dos execuatbles and batch files specified via a linux path at dosemu launch time. I tracked that problem down to unix.c trying to convert linux path to dos path using find_drive which currently relies on mfs and consequently cds being available.  Since all that is required is to establish where the dos drive (if fatfs linux directory based) has its root. So that prefix can be removed from the full linux path, I only see it necessary to find the drives root and not fix the whole redirector to work without cds.

**Comment by stsp** [comment]
> but for now the only ill effect im seeing due to the redirector being un available is the inability
> to execute dos execuatbles and batch files specified via a linux path

No, this is not in the list of the problems.
If you are running without redirector, you have an FS that is:
- slow
- read only
- limited to the geometry in disks.c (2Gb?)
And you can't use lredir to mount new drives.
I'd say this is a waste of time.

It would nevertheless be nice to allow unix.com to work
without the redirector and use fatfs as a fall-back, but this
doesn't help with the task of supporting new doses.
But I can't see why your patch is correct.
You seem to be doing get_fat_fs_by_drive() when _first_
drive is found that does not have the redirection. You
probably want to probe all drives that have no redirection,
not just the first one?

In any case, this find_drive() is a perfect example of the
jack-ass code. Would you mind sanitizing it before adding
new features?

**Comment by andrewbird** [comment]
Yep, I think I got the logic wrong, and just got lucky in testing with a single drive! I'm losing the will to mess with this much more. All I want for my basic OS boot test is for 'unix.com -e' to be able to either:
- run a batch file specified with linux path, i.e. 'version.bat' that contains just 'ver'
- run an internal DOS command i.e. 'ver'

I would hope that would not require the redirector to work, but yes I understand your concerns about usability of the system if an OS does boot, but doesn't have working disk redirection.

**Comment by stsp** [comment]
> Yep, I think I got the logic wrong, and just got lucky in testing with a single drive!

When you don't understand the logic of dosemu code -
re-write it! :) dosemu is an example of the worst code
in the world, in most places.

> I would hope that would not require the redirector to work, but yes I understand
> your concerns about usability of the system if an OS does boot, but doesn't have
> working disk redirection.

Someone should really study the ways of improving the
redirector.

**Comment by stsp** [comment]
OK, so lets close this.
It would be really cool if you investigate
the possibilities of improving our redirector,
even without doing the actual coding.
Some research would be good, and I won't have
time for this in any near future.

**Pull request closed without merging**
