### PR TITLE
Travis: Add DOS v2 FindFirst/FindNext mixed DTA tests

### PR DESCRIPTION
**Pull request by andrewbird**
Start two FindFirst (one wild, one plain) with different DTAs,
then check we get a proper result with FindNext using the first
DTA. See PR #1010

Thanks to @bartoldeman for the skeleton test in NASM

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!

**Comment by stsp** [comment]
I have unmerged this as it seems to
fail the test after all. :(
Could you please re-create the pr?

**Comment by andrewbird** [comment]
I will open another PR in a moment (I renamed the tests a little). I've now rebased against current devel, but the mfs test is still failing. Is that what you expect?

**Comment by stsp** [comment]
Why would I expect that, if yesterday
it was passing?

**Comment by andrewbird** [comment]
It was passing at one point against getdir branch, but never against devel. If further changes to getdir occurred it would not have retested. I think the thought process behind this is that the branch to be merged in (mine) is watched for changes. I figure you don't want to merge my branch until your new stuff is working, so probably the best way to do this is to cherry-pick the single commit from mine and test locally.

**Comment by stsp** [comment]
But I merged the getdir branch and then
merged this. I didn't know it won't work
that way.

**Comment by andrewbird** [comment]
I guess it could work the other way around, merge the getdir branch into the new test branch, then any more changes to getdir would trigger the retest, but I don't really know.

**Comment by andrewbird** [comment]
New PR is #1014 against devel

**Pull request merged**
