### PR TITLE
Simx86 & vgaemu speedups (3rd try)

### PR DESCRIPTION
**Pull request by bartoldeman**
I haven't addressed all comments from #149, so please do not merge and not close either. But you can use it to check Prehistorik 2 performance with the JIT.

### CODE REVIEW

**Comment by stsp** [comment]
Yes, this fixes the jit slowdown completely!
Excellent work!
Btw, looks like the gfx glitch is not only in the
shaking. There are other problems too on the
same screens where the shaking happens.
Namely, the screen is not always filled with
the floating prehistorik images - sometimes
the bottom of the screen is empty.

**Comment by stsp** [comment]
Hi Bart, any chances to get this in?
Would be nice to get prehistorik finally working.
Looks like we have quite a lot of the "fix" branches
like this, with no activity. :(

**Comment by bartoldeman** [comment]
Hi Stas,
thanks for your interest getting this in. I haven't had a lot of time, and put some priority to KVM, but I'll look back at this soon.

**Comment by stsp** [comment]
Hi Bart, I suppose with this patch set we can
also disable the hack at vgaemu.c:1106?

**Comment by bartoldeman** [comment]
Superseded by #1056 and related earlier patches mentioned here.

The patches not merged into devel are signal handling cleanups which were already done earlier.

**Pull request closed without merging**
